#!/usr/bin/env python3
# Generated by Serpen - Python Source Bundler
# https://github.com/tinovyatkin/serpen

# ─ Module: test_module ─
#!/usr/bin/env python3
"""A test module with various utilities."""


def utility_function():
    """A simple utility function."""
    return "utility result"


class TestClass:
    """A test class."""

    def __init__(self, value):
        self.value = value

    def get_value(self):
        return self.value


# Some constants
CONSTANT_VALUE = 42

# ─ Entry Module: test_simple_alias ─
#!/usr/bin/env python3
"""Simple test file to verify aliased import detection."""


def main():
    result = tm.utility_function()
    print(result)


if __name__ == "__main__":
    main()
