#!/usr/bin/env python3
# Generated by Cribo - Python Source Bundler
# https://github.com/ophidiarium/cribo

# ─ Module: greetings.greeting ─
message = "Hello"
message = message

# ─ Module: greetings ─
import types

greetings = types.ModuleType("greetings")
exec('message = message\n__all__ = ["message"]', globals(), greetings.__dict__)

# ─ Entry Module: hello ─
print(greetings.message)
