#!/usr/bin/env python3
# Generated by Cribo - Python Source Bundler
# https://github.com/ophidiarium/cribo

# ─ Module: greetings.greeting ─
import types

greetings = types.ModuleType("greetings")
greetings.greeting = types.ModuleType("greetings.greeting")
exec('message = "Hello"', greetings.greeting.__dict__)

# ─ Module: greetings ─
exec('message = greetings.greeting.message\n__all__ = ["message"]', globals(), greetings.__dict__)

# ─ Entry Module: hello ─
print(greetings.message)
